# Generated by Django 4.2.2 on 2023-06-27 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_corgis_corgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=10)),
                ('color', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], default='female', max_length=10)),
                ('corgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='main_app.corgi')),
            ],
        ),
    ]
