# Generated by Django 4.2.2 on 2023-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_dog_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dogs', models.ManyToManyField(to='main_app.dog')),
            ],
        ),
    ]
